#!/bin/sh
# convenience script to build libwolfssl.ko on FreeBSD.

if [ $# -eq 0 ]; then
  echo "register build"; sleep 1;
  ./configure --enable-freebsdkm --enable-cryptonly \
    --enable-crypttests --enable-freebsdkm-crypto-register \
    --enable-aesgcm-stream \
    CFLAGS="-DWOLFSSL_BSDKM_VERBOSE_DEBUG" \
    || exit 1
elif [ $# -eq 1 ]; then
  echo "normal build"; sleep 1;
  ./configure --enable-freebsdkm --enable-cryptonly \
    --enable-crypttests  --enable-all-crypto \
    --enable-fips=disabled --enable-debug \
    CFLAGS="-DWOLFSSL_BSDKM_VERBOSE_DEBUG" \
    || exit 1
else
  echo "normal fips build"; sleep 1;
  ./configure --enable-freebsdkm --enable-cryptonly \
    --enable-crypttests --enable-all-crypto \
    --enable-fips=dev --enable-debug \
    CFLAGS="-DWOLFSSL_BSDKM_VERBOSE_DEBUG -DDEBUG_FIPS_VERBOSE" \
    || exit 1
fi

make && sudo kldload bsdkm/libwolfssl.ko || exit 1

dmesg | tail -n5

if [ $# -eq 0 ]; then
  kldstat -m nexus/libwolfssl
else
  kldstat -m libwolfssl
fi

echo "load done"
